name: Sync to Coding

on:
  push:
    branches: [main, gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --all
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
            git branch --track ${branch##*/} $branch
          done
      - name: Push to Coding
        run: |
          remote_repo="https://${CODING_USERNAME}:${CODING_PASSWORD}@e.coding.net/${CODING_REPOSITORY}.git"
          git remote add coding "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose
          # publish all
          git push --all --force coding
          git push --tags --force coding
        env:
          GITHUB_REPOSITORY: cuilongjin/hexo-blog
          CODING_REPOSITORY: cuilongjin/hexo-blog
          CODING_USERNAME: ${{ secrets.CODING_USERNAME }}
          CODING_PASSWORD: ${{ secrets.CODING_PASSWORD }}
